ALTER TABLE "User"
ALTER COLUMN "passwordHash" TYPE VARCHAR(255);

ALTER TABLE "User"
ALTER COLUMN "name" TYPE VARCHAR(120);

ALTER TABLE "User"
ALTER COLUMN "avatarUrl" TYPE TEXT;

ALTER TABLE "User"
ALTER COLUMN "timezone" TYPE VARCHAR(120);

ALTER TABLE "User"
ALTER COLUMN "googleId" TYPE VARCHAR(255);

ALTER TABLE "MuscleGroup"
ALTER COLUMN "name" TYPE VARCHAR(120);

ALTER TABLE "MuscleGroup"
ALTER COLUMN "imageUrl" TYPE TEXT;

ALTER TABLE "MuscleGroup"
ALTER COLUMN "iconUrl" TYPE TEXT;

ALTER TABLE "Equipment"
ALTER COLUMN "name" TYPE VARCHAR(120);

ALTER TABLE "Equipment"
ALTER COLUMN "iconUrl" TYPE TEXT;

ALTER TABLE "ExerciseVideo"
ALTER COLUMN "url" TYPE TEXT;

ALTER TABLE "ExerciseVideo"
ALTER COLUMN "title" TYPE VARCHAR(255);

ALTER TABLE "ExerciseVideo"
ALTER COLUMN "thumbnailUrl" TYPE TEXT;

ALTER TABLE "WorkoutTemplateExercise"
ALTER COLUMN "supersetGroupKey" TYPE VARCHAR(64);

ALTER TABLE "SessionExercise"
ALTER COLUMN "supersetGroupKey" TYPE VARCHAR(64);

ALTER TABLE "Set"
ALTER COLUMN "idempotencyKey" TYPE VARCHAR(128);
